name: frontend-docker-image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name : Set Secrets
        run : |
            export API_URL_=${{ secrets.API_URL_S }}
            export API_KEY_=${{ secrets.API_KEY_S }}
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./Frontend/dsw-project --build-arg API_URL_=${{ secrets.API_URL_S }} --build-arg API_KEY_=${{ secrets.API_KEY_S }} --file ./Frontend/dsw-project/Dockerfile --tag ${{ secrets.DOCKER_FRONTEND_IMAGE }}:$(date +%s)
